-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local developerProducts_1 = require(game.ReplicatedStorage.SharedModules.SharedProductIds).developerProducts
local tbl_1 = {Slot = "Charm", DisplayName = "Charm Chest", CardName = "CharmChestTemplate", Section = "CloudChests", ExhaustedCoins = 500, Category = "Charms"}
tbl_1.ProductId = developerProducts_1.CharmChest
tbl_1.BundleProductId = developerProducts_1.CharmChest_x3
tbl_1.GiftProductId = developerProducts_1.GIFT_CharmChest
tbl_1.Pool = {
    {Weight = 104, ItemId = "Hair Clips"},
    {Weight = 98, ItemId = "Bandaids"},
    {Weight = 81, ItemId = "Cap"},
    {Weight = 74, ItemId = "Glasses"},
    {Weight = 68, ItemId = "Seedling"},
    {Weight = 50, ItemId = "Beanie"},
    {Weight = 43, ItemId = "Cat Ears"},
    {Weight = 41, ItemId = "Rabbit Ears"},
    {Weight = 38, ItemId = "Starlings"},
    {Weight = 36, ItemId = "Wolf Ears"},
    {Weight = 27, ItemId = "Heart Glasses"},
    {Weight = 25, ItemId = "Horns"},
    {Weight = 27, ItemId = "Kawai Beanie"},
    {Weight = 24, ItemId = "Tiara"},
    {Weight = 24, ItemId = "Butterfly Bow Tie"},
    {Weight = 25, ItemId = "Star Glasses"},
    {Weight = 19, ItemId = "White Bow Tie"},
    {Weight = 8, ItemId = "Crown"}
}
return tbl_1