-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local developerProducts_1 = require(game.ReplicatedStorage.SharedModules.SharedProductIds).developerProducts
local tbl_1 = {Slot = "Cloud", Unavailable = false, DisplayName = "Cloud Chest", CardName = "CloudChestTemplate", Section = "CloudChests", ExhaustedCoins = 500, Category = "Clouds"}
tbl_1.ProductId = developerProducts_1.CloudChest
tbl_1.BundleProductId = developerProducts_1.CloudChest_x3
tbl_1.GiftProductId = developerProducts_1.GIFT_CloudChest
tbl_1.Pool = {
    {Weight = 94, ItemId = "Cyan"},
    {Weight = 83, ItemId = "Orange"},
    {Weight = 72, ItemId = "Peach"},
    {Weight = 61, ItemId = "Pink"},
    {Weight = 53, ItemId = "Purple"},
    {Weight = 43, ItemId = "Blue"},
    {Weight = 37, ItemId = "Green"},
    {Weight = 32, ItemId = "Red"},
    {Weight = 30, ItemId = "White"},
    {Weight = 26, ItemId = "Angel"},
    {Weight = 26, ItemId = "Angry"},
    {Weight = 24, ItemId = "Good"},
    {Weight = 22, ItemId = "Santa"},
    {Weight = 11, ItemId = "Devil"},
    {Weight = 11, ItemId = "Storm"},
    {Weight = 6, ItemId = "Wise"}
}
return tbl_1