-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local RuntimeLib_1 = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib"))
local GAME_METADATA_1 = RuntimeLib_1.import(script, game:GetService("ReplicatedStorage"), "TS", "games", "game-metadata").GAME_METADATA
local CrossyRoadGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "crossy-road", "crossy-road-game").CrossyRoadGame
local DinoRunGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "dino-run", "dino-run-game").DinoRunGame
local DoodleJumpGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "doodle-jump", "doodle-jump-game").DoodleJumpGame
local DunkShotGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "dunk-shot", "dunk-shot-game").DunkShotGame
local FlappyBasketGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "flappy-basket", "flappy-basket-game").FlappyBasketGame
local FlappyBirdGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "flappy-bird", "flappy-bird-game").FlappyBirdGame
local FruitNinjaGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "fruit-ninja", "fruit-ninja-game").FruitNinjaGame
local Game2048_upv_1 = RuntimeLib_1.import(script, script.Parent, "game-2048", "game-2048").Game2048
local Game2048View_1 = RuntimeLib_1.import(script, script.Parent, "game-2048", "game-2048-view").Game2048View
local Game2048WorldGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "game-2048-3d", "game-2048-3d-game").Game2048WorldGame
local HelixJumpGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "helix-jump", "helix-jump-game").HelixJumpGame
local HighwayRiderGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "highway-rider", "highway-rider-game").HighwayRiderGame
local IcyTowerGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "icy-tower", "icy-tower-game").IcyTowerGame
local KnifeHitGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "knife-hit", "knife-hit-game").KnifeHitGame
local NumberMergeGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "number-merge", "number-merge").NumberMergeGame
local NumberMergeView_1 = RuntimeLib_1.import(script, script.Parent, "number-merge", "number-merge-view").NumberMergeView
local BallzGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "ballz", "ballz-game").BallzGame
local PongGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "pong", "pong-game").PongGame
local SnakeGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "snake", "snake-game").SnakeGame
local HillClimbGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "hill-climb", "hill-climb-game").HillClimbGame
local StackBallGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "stack-ball", "stack-ball-game").StackBallGame
local StickmanHookGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "stickman-hook", "stickman-hook-game").StickmanHookGame
local BloxorzGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "bloxorz", "bloxorz-game").BloxorzGame
local CookieClickerGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "cookie-clicker", "cookie-clicker-game").CookieClickerGame
local CookieClickerView_1 = RuntimeLib_1.import(script, script.Parent, "cookie-clicker", "cookie-clicker-view").CookieClickerView
local TrafficRushGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "traffic-rush", "traffic-rush-game").TrafficRushGame
local BlockBlastGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "block-blast", "block-blast-game").BlockBlastGame
local UnblockMeGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "unblock-me", "unblock-me-game").UnblockMeGame
local SokobanGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "sokoban", "sokoban-game").SokobanGame
local WaterSortGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "water-sort", "water-sort-game").WaterSortGame
local FlowFreeGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "flow-free", "flow-free-game").FlowFreeGame
local MinesweeperGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "minesweeper", "minesweeper-game").MinesweeperGame
local LightsOutGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "lights-out", "lights-out-game").LightsOutGame
local OnetGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "onet", "onet-game").OnetGame
local FlippyKnifeGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "flippy-knife", "flippy-knife-game").FlippyKnifeGame
local DunkHitGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "dunk-hit", "dunk-hit-game").DunkHitGame
local HopGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "hop", "hop-game").HopGame
local JellyJumpGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "jelly-jump", "jelly-jump-game").JellyJumpGame
local SlingDriftGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "sling-drift", "sling-drift-game").SlingDriftGame
local StackGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "stack", "stack-game").StackGame
local TetrisGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "tetris", "tetris-game").TetrisGame
local SuikaGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "suika", "suika-game").SuikaGame
local TimbermanGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "timberman", "timberman-game").TimbermanGame
local TinyWingsGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "tiny-wings", "tiny-wings-game").TinyWingsGame
local TowerBuilderGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "tower-builder", "tower-builder-game").TowerBuilderGame
local ZigZagGame_upv_1 = RuntimeLib_1.import(script, script.Parent, "zig-zag", "zig-zag-game").ZigZagGame
local tbl_1 = {}
local function create_1(a1)
    --[[
      name: create
      line: 66
      upvalues:
        FlappyBirdGame_upv_1 (copy, index: 1)
    ]]
    return FlappyBirdGame_upv_1.new(a1)
end
tbl_1["flappy-bird"] = {metadata = GAME_METADATA_1["flappy-bird"], create = create_1}
local function create_2(a1)
    --[[
      name: create
      line: 74
      upvalues:
        Game2048_upv_1 (copy, index: 1)
    ]]
    return Game2048_upv_1.new(a1)
end
tbl_1["2048"] = {metadata = GAME_METADATA_1["2048"], create = create_2, View = Game2048View_1}
local function create_3(a1)
    --[[
      name: create
      line: 86
      upvalues:
        Game2048WorldGame_upv_1 (copy, index: 1)
    ]]
    return Game2048WorldGame_upv_1.new(a1)
end
tbl_1["2048-3d"] = {metadata = GAME_METADATA_1["2048-3d"], create = create_3}
local function create_4(a1)
    --[[
      name: create
      line: 97
      upvalues:
        StackGame_upv_1 (copy, index: 1)
    ]]
    return StackGame_upv_1.new(a1)
end
tbl_1.stack = {metadata = GAME_METADATA_1.stack, create = create_4}
local function create_5(a1)
    --[[
      name: create
      line: 106
      upvalues:
        KnifeHitGame_upv_1 (copy, index: 1)
    ]]
    return KnifeHitGame_upv_1.new(a1)
end
tbl_1["knife-hit"] = {metadata = GAME_METADATA_1["knife-hit"], create = create_5}
local function create_6(a1)
    --[[
      name: create
      line: 115
      upvalues:
        HelixJumpGame_upv_1 (copy, index: 1)
    ]]
    return HelixJumpGame_upv_1.new(a1)
end
tbl_1["helix-jump"] = {metadata = GAME_METADATA_1["helix-jump"], create = create_6}
local function create_7(a1)
    --[[
      name: create
      line: 124
      upvalues:
        TimbermanGame_upv_1 (copy, index: 1)
    ]]
    return TimbermanGame_upv_1.new(a1)
end
tbl_1.timberman = {metadata = GAME_METADATA_1.timberman, create = create_7}
local function create_8(a1)
    --[[
      name: create
      line: 133
      upvalues:
        NumberMergeGame_upv_1 (copy, index: 1)
    ]]
    return NumberMergeGame_upv_1.new(a1)
end
tbl_1["number-merge"] = {metadata = GAME_METADATA_1["number-merge"], create = create_8, View = NumberMergeView_1}
local function create_9(a1)
    --[[
      name: create
      line: 144
      upvalues:
        ZigZagGame_upv_1 (copy, index: 1)
    ]]
    return ZigZagGame_upv_1.new(a1)
end
tbl_1["zig-zag"] = {metadata = GAME_METADATA_1["zig-zag"], create = create_9}
local function create_10(a1)
    --[[
      name: create
      line: 152
      upvalues:
        FruitNinjaGame_upv_1 (copy, index: 1)
    ]]
    return FruitNinjaGame_upv_1.new(a1)
end
tbl_1["fruit-ninja"] = {metadata = GAME_METADATA_1["fruit-ninja"], create = create_10}
local function create_11(a1)
    --[[
      name: create
      line: 162
      upvalues:
        SuikaGame_upv_1 (copy, index: 1)
    ]]
    return SuikaGame_upv_1.new(a1)
end
tbl_1.suika = {metadata = GAME_METADATA_1.suika, create = create_11}
local function create_12(a1)
    --[[
      name: create
      line: 173
      upvalues:
        CrossyRoadGame_upv_1 (copy, index: 1)
    ]]
    return CrossyRoadGame_upv_1.new(a1)
end
tbl_1["crossy-road"] = {metadata = GAME_METADATA_1["crossy-road"], create = create_12}
local function create_13(a1)
    --[[
      name: create
      line: 181
      upvalues:
        DoodleJumpGame_upv_1 (copy, index: 1)
    ]]
    return DoodleJumpGame_upv_1.new(a1)
end
tbl_1["doodle-jump"] = {metadata = GAME_METADATA_1["doodle-jump"], create = create_13}
local function create_14(a1)
    --[[
      name: create
      line: 190
      upvalues:
        HighwayRiderGame_upv_1 (copy, index: 1)
    ]]
    return HighwayRiderGame_upv_1.new(a1, "tp")
end
tbl_1["highway-rider-tp"] = {metadata = GAME_METADATA_1["highway-rider-tp"], create = create_14}
local function create_15(a1)
    --[[
      name: create
      line: 199
      upvalues:
        HighwayRiderGame_upv_1 (copy, index: 1)
    ]]
    return HighwayRiderGame_upv_1.new(a1, "fp")
end
tbl_1["highway-rider-fp"] = {metadata = GAME_METADATA_1["highway-rider-fp"], create = create_15}
local function create_16(a1)
    --[[
      name: create
      line: 208
      upvalues:
        HighwayRiderGame_upv_1 (copy, index: 1)
    ]]
    return HighwayRiderGame_upv_1.new(a1, "fp", {})
end
tbl_1["highway-rider-fp-test"] = {metadata = GAME_METADATA_1["highway-rider-fp-test"], create = create_16}
local function create_17(a1)
    --[[
      name: create
      line: 219
      upvalues:
        DinoRunGame_upv_1 (copy, index: 1)
    ]]
    return DinoRunGame_upv_1.new(a1)
end
tbl_1["dino-run"] = {metadata = GAME_METADATA_1["dino-run"], create = create_17}
local function create_18(a1)
    --[[
      name: create
      line: 228
      upvalues:
        SnakeGame_upv_1 (copy, index: 1)
    ]]
    return SnakeGame_upv_1.new(a1)
end
tbl_1.snake = {metadata = GAME_METADATA_1.snake, create = create_18}
local function create_19(a1)
    --[[
      name: create
      line: 237
      upvalues:
        TinyWingsGame_upv_1 (copy, index: 1)
    ]]
    return TinyWingsGame_upv_1.new(a1)
end
tbl_1["tiny-wings"] = {metadata = GAME_METADATA_1["tiny-wings"], create = create_19}
local function create_20(a1)
    --[[
      name: create
      line: 246
      upvalues:
        TetrisGame_upv_1 (copy, index: 1)
    ]]
    return TetrisGame_upv_1.new(a1)
end
tbl_1.tetris = {metadata = GAME_METADATA_1.tetris, create = create_20}
local function create_21(a1)
    --[[
      name: create
      line: 257
      upvalues:
        IcyTowerGame_upv_1 (copy, index: 1)
    ]]
    return IcyTowerGame_upv_1.new(a1)
end
tbl_1["icy-tower"] = {metadata = GAME_METADATA_1["icy-tower"], create = create_21}
local function create_22(a1)
    --[[
      name: create
      line: 265
      upvalues:
        FlappyBasketGame_upv_1 (copy, index: 1)
    ]]
    return FlappyBasketGame_upv_1.new(a1)
end
tbl_1["flappy-basket"] = {metadata = GAME_METADATA_1["flappy-basket"], create = create_22}
local function create_23(a1)
    --[[
      name: create
      line: 273
      upvalues:
        TowerBuilderGame_upv_1 (copy, index: 1)
    ]]
    return TowerBuilderGame_upv_1.new(a1)
end
tbl_1["tower-builder"] = {metadata = GAME_METADATA_1["tower-builder"], create = create_23}
local function create_24(a1)
    --[[
      name: create
      line: 282
      upvalues:
        PongGame_upv_1 (copy, index: 1)
    ]]
    return PongGame_upv_1.new(a1)
end
tbl_1.pong = {metadata = GAME_METADATA_1.pong, create = create_24}
local function create_25(a1)
    --[[
      name: create
      line: 292
      upvalues:
        DunkShotGame_upv_1 (copy, index: 1)
    ]]
    return DunkShotGame_upv_1.new(a1)
end
tbl_1["dunk-shot"] = {metadata = GAME_METADATA_1["dunk-shot"], create = create_25}
local function create_26(a1)
    --[[
      name: create
      line: 301
      upvalues:
        BallzGame_upv_1 (copy, index: 1)
    ]]
    return BallzGame_upv_1.new(a1)
end
tbl_1.ballz = {metadata = GAME_METADATA_1.ballz, create = create_26}
local function create_27(a1)
    --[[
      name: create
      line: 311
      upvalues:
        StackBallGame_upv_1 (copy, index: 1)
    ]]
    return StackBallGame_upv_1.new(a1)
end
tbl_1["stack-ball"] = {metadata = GAME_METADATA_1["stack-ball"], create = create_27}
local function create_28(a1)
    --[[
      name: create
      line: 320
      upvalues:
        HillClimbGame_upv_1 (copy, index: 1)
    ]]
    return HillClimbGame_upv_1.new(a1)
end
tbl_1["hill-climb"] = {metadata = GAME_METADATA_1["hill-climb"], create = create_28}
local function create_29(a1)
    --[[
      name: create
      line: 330
      upvalues:
        StickmanHookGame_upv_1 (copy, index: 1)
    ]]
    return StickmanHookGame_upv_1.new(a1)
end
tbl_1["stickman-hook"] = {metadata = GAME_METADATA_1["stickman-hook"], create = create_29}
local function create_30(a1)
    --[[
      name: create
      line: 340
      upvalues:
        BloxorzGame_upv_1 (copy, index: 1)
    ]]
    return BloxorzGame_upv_1.new(a1)
end
tbl_1.bloxorz = {metadata = GAME_METADATA_1.bloxorz, create = create_30}
local function create_31(a1)
    --[[
      name: create
      line: 350
      upvalues:
        CookieClickerGame_upv_1 (copy, index: 1)
    ]]
    return CookieClickerGame_upv_1.new(a1)
end
tbl_1["cookie-clicker"] = {metadata = GAME_METADATA_1["cookie-clicker"], create = create_31, View = CookieClickerView_1}
local function create_32(a1)
    --[[
      name: create
      line: 360
      upvalues:
        TrafficRushGame_upv_1 (copy, index: 1)
    ]]
    return TrafficRushGame_upv_1.new(a1)
end
tbl_1["traffic-rush"] = {metadata = GAME_METADATA_1["traffic-rush"], create = create_32}
local function create_33(a1)
    --[[
      name: create
      line: 369
      upvalues:
        BlockBlastGame_upv_1 (copy, index: 1)
    ]]
    return BlockBlastGame_upv_1.new(a1)
end
tbl_1["block-blast"] = {metadata = GAME_METADATA_1["block-blast"], create = create_33}
local function create_34(a1)
    --[[
      name: create
      line: 379
      upvalues:
        UnblockMeGame_upv_1 (copy, index: 1)
    ]]
    return UnblockMeGame_upv_1.new(a1)
end
tbl_1["unblock-me"] = {metadata = GAME_METADATA_1["unblock-me"], create = create_34}
local function create_35(a1)
    --[[
      name: create
      line: 389
      upvalues:
        SokobanGame_upv_1 (copy, index: 1)
    ]]
    return SokobanGame_upv_1.new(a1)
end
tbl_1.sokoban = {metadata = GAME_METADATA_1.sokoban, create = create_35}
local function create_36(a1)
    --[[
      name: create
      line: 399
      upvalues:
        WaterSortGame_upv_1 (copy, index: 1)
    ]]
    return WaterSortGame_upv_1.new(a1)
end
tbl_1["water-sort"] = {metadata = GAME_METADATA_1["water-sort"], create = create_36}
local function create_37(a1)
    --[[
      name: create
      line: 410
      upvalues:
        FlowFreeGame_upv_1 (copy, index: 1)
    ]]
    return FlowFreeGame_upv_1.new(a1)
end
tbl_1["flow-free"] = {metadata = GAME_METADATA_1["flow-free"], create = create_37}
local function create_38(a1)
    --[[
      name: create
      line: 420
      upvalues:
        MinesweeperGame_upv_1 (copy, index: 1)
    ]]
    return MinesweeperGame_upv_1.new(a1)
end
tbl_1.minesweeper = {metadata = GAME_METADATA_1.minesweeper, create = create_38}
local function create_39(a1)
    --[[
      name: create
      line: 430
      upvalues:
        LightsOutGame_upv_1 (copy, index: 1)
    ]]
    return LightsOutGame_upv_1.new(a1)
end
tbl_1["lights-out"] = {metadata = GAME_METADATA_1["lights-out"], create = create_39}
local function create_40(a1)
    --[[
      name: create
      line: 440
      upvalues:
        FlippyKnifeGame_upv_1 (copy, index: 1)
    ]]
    return FlippyKnifeGame_upv_1.new(a1)
end
tbl_1["flippy-knife"] = {metadata = GAME_METADATA_1["flippy-knife"], create = create_40}
local function create_41(a1)
    --[[
      name: create
      line: 449
      upvalues:
        DunkHitGame_upv_1 (copy, index: 1)
    ]]
    return DunkHitGame_upv_1.new(a1)
end
tbl_1["dunk-hit"] = {metadata = GAME_METADATA_1["dunk-hit"], create = create_41}
local function create_42(a1)
    --[[
      name: create
      line: 458
      upvalues:
        HopGame_upv_1 (copy, index: 1)
    ]]
    return HopGame_upv_1.new(a1)
end
tbl_1.hop = {metadata = GAME_METADATA_1.hop, create = create_42}
local function create_43(a1)
    --[[
      name: create
      line: 467
      upvalues:
        JellyJumpGame_upv_1 (copy, index: 1)
    ]]
    return JellyJumpGame_upv_1.new(a1)
end
tbl_1["jelly-jump"] = {metadata = GAME_METADATA_1["jelly-jump"], create = create_43}
local function create_44(a1)
    --[[
      name: create
      line: 476
      upvalues:
        SlingDriftGame_upv_1 (copy, index: 1)
    ]]
    return SlingDriftGame_upv_1.new(a1)
end
tbl_1["sling-drift"] = {metadata = GAME_METADATA_1["sling-drift"], create = create_44}
local function create_45(a1)
    --[[
      name: create
      line: 485
      upvalues:
        OnetGame_upv_1 (copy, index: 1)
    ]]
    return OnetGame_upv_1.new(a1)
end
tbl_1.onet = {metadata = GAME_METADATA_1.onet, create = create_45}
local tbl_2 = {}
tbl_2.GAME_REGISTRY = tbl_1
return tbl_2