-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {}
tbl_1.backdropColor = Color3.fromRGB(118, 160, 196)
tbl_1.groundColor = Color3.fromRGB(150, 128, 58)
tbl_1.hillColor = Color3.fromRGB(104, 78, 46)
tbl_1.pineTrunkColor = Color3.fromRGB(74, 52, 34)
tbl_1.pineLeafColor = Color3.fromRGB(168, 96, 38)
tbl_1.trunkColor = Color3.fromRGB(142, 94, 58)
tbl_1.trunkAltColor = Color3.fromRGB(128, 84, 50)
tbl_1.branchColor = Color3.fromRGB(206, 128, 48)
tbl_1.celestialColor = Color3.fromRGB(255, 224, 130)
local tbl_2 = {}
tbl_2.backdropColor = Color3.fromRGB(172, 190, 208)
tbl_2.groundColor = Color3.fromRGB(226, 232, 240)
tbl_2.hillColor = Color3.fromRGB(196, 208, 222)
tbl_2.pineTrunkColor = Color3.fromRGB(66, 52, 44)
tbl_2.pineLeafColor = Color3.fromRGB(70, 110, 96)
tbl_2.trunkColor = Color3.fromRGB(112, 76, 50)
tbl_2.trunkAltColor = Color3.fromRGB(100, 67, 44)
tbl_2.branchColor = Color3.fromRGB(214, 232, 228)
tbl_2.celestialColor = Color3.fromRGB(244, 248, 252)
local tbl_3 = {}
tbl_3.backdropColor = Color3.fromRGB(186, 88, 64)
tbl_3.groundColor = Color3.fromRGB(96, 118, 60)
tbl_3.hillColor = Color3.fromRGB(66, 38, 48)
tbl_3.pineTrunkColor = Color3.fromRGB(46, 30, 30)
tbl_3.pineLeafColor = Color3.fromRGB(40, 52, 42)
tbl_3.trunkColor = Color3.fromRGB(128, 78, 50)
tbl_3.trunkAltColor = Color3.fromRGB(114, 68, 44)
tbl_3.branchColor = Color3.fromRGB(76, 132, 62)
tbl_3.celestialColor = Color3.fromRGB(255, 170, 92)
local tbl_4 = {{backdropColor = Color3.fromRGB(12, 14, 18), groundColor = Color3.fromRGB(106, 170, 80), hillColor = Color3.fromRGB(18, 30, 24), pineTrunkColor = Color3.fromRGB(52, 38, 28), pineLeafColor = Color3.fromRGB(26, 52, 34), trunkColor = Color3.fromRGB(134, 88, 54), trunkAltColor = Color3.fromRGB(122, 79, 48), branchColor = Color3.fromRGB(88, 166, 70), celestialColor = Color3.fromRGB(235, 235, 210)}, tbl_1, tbl_2, tbl_3}
local tbl_5 = {}
tbl_5.TIMBERMAN_THEMES = tbl_4
return tbl_5