-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local atom_1 = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib")).import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@rbxts", "charm", "src").atom
local tbl_1 = {}
tbl_1.numberMergeBoardAtom = atom_1(nil)
tbl_1.numberMergeControlsAtom = atom_1(nil)
return tbl_1