-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Uncommon", Cost = 6000, CosmeticName = "Boba Skin Pack", ShopThumbnailImageId = "rbxassetid://120081929201900", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://16491125847"}
tbl_1.FruitBox = {Image = "rbxassetid://16491126235", TopBarColor = Color3.fromRGB(255, 188, 213)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://16491131493", Size = UDim2.new(0, 85, 0, 85), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [2] = {Image = "rbxassetid://16491131163", Size = UDim2.new(0, 120, 0, 140), Position = UDim2.new(0.49000001, 0, 0.49000001, 0)},
    [3] = {Image = "rbxassetid://16491130883", Size = UDim2.new(0, 180, 0, 190), Position = UDim2.new(0.479999989, 0, 0.5, 0)},
    [4] = {Image = "rbxassetid://16491130662", Size = UDim2.new(0, 187, 0, 188), Position = UDim2.new(0.493000001, 0, 0.5, 0)},
    [5] = {Image = "rbxassetid://16491130368", Size = UDim2.new(0, 227, 0, 225), Position = UDim2.new(0.495000005, 0, 0.5, 0)},
    [6] = {Image = "rbxassetid://16491130030", Size = UDim2.new(0, 310, 0, 310), Position = UDim2.new(0.493000001, 0, 0.493999988, 0)},
    [7] = {Image = "rbxassetid://16491129495", Size = UDim2.new(0, 397, 0, 339), Position = UDim2.new(0.493000001, 0, 0.49000001, 0)},
    [8] = {Image = "rbxassetid://16491128656", Size = UDim2.new(0, 436, 0, 441), Position = UDim2.new(0.493000001, 0, 0.5, 0)},
    [9] = {Image = "rbxassetid://16491128276", Size = UDim2.new(0, 463, 0, 499), Position = UDim2.new(0.49000001, 0, 0.493000001, 0)},
    [10] = {Image = "rbxassetid://16491128088", Size = UDim2.new(0, 675, 0, 571), Position = UDim2.new(0.493000001, 0, 0.497999996, 0)},
    [11] = {Image = "rbxassetid://16491127846", Size = UDim2.new(0, 490, 0, 621), Position = UDim2.new(0.493999988, 0, 0.495000005, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://15044243217", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.new(0.384313762, 0.231372565, 0.164705887), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 238, 191)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 195, 84))}), CurrentScoreStrokeColor = Color3.fromRGB(74, 30, 8)},
    NextFruit = {
        Image = "rbxassetid://15044243766",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {Cherry = {Image = "rbxassetid://16491131493", Size = UDim2.new(0.788835049, 0, 0.788835347, 0)}, Strawberry = {Image = "rbxassetid://16491131163", Size = UDim2.new(1.05091631, 0, 1.05091631, 0)}, Grapes = {Image = "rbxassetid://16491130883", Size = UDim2.new(1.2014854, 0, 1.20148563, 0)}, Orange = {Image = "rbxassetid://16491130662", Size = UDim2.new(1.3501066, 0, 1.35010648, 0)}, Tomato = {Image = "rbxassetid://16491130368", Size = UDim2.new(1.43700516, 0, 1.4370048, 0)}}
    },
    Info = {DropButtonImage = "rbxassetid://16491370217", InfographicImage = "rbxassetid://16491371827"},
    MobileControls = {MoveRightImage = "rbxassetid://15300845665", MoveLeftImage = "rbxassetid://15300845942"}
}
return tbl_1