-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Uncommon", Cost = 7500, CosmeticName = "Celestial Skin Pack", ShopThumbnailImageId = "rbxassetid://77432576076549", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://16674059391"}
tbl_1.FruitBox = {Image = "rbxassetid://16581199205", TopBarColor = Color3.fromRGB(255, 255, 255)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://16673779745", Size = UDim2.new(0, 56, 0, 56), Position = UDim2.new(0.545000017, 0, 0.5, 0)},
    [2] = {Image = "rbxassetid://16673779601", Size = UDim2.new(0, 89, 0, 79), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [3] = {Image = "rbxassetid://16673779236", Size = UDim2.new(0, 123, 0, 136), Position = UDim2.new(0.5, 0, 0.504999995, 0)},
    [4] = {Image = "rbxassetid://16673778944", Size = UDim2.new(0, 129, 0, 129), Position = UDim2.new(0.50999999, 0, 0.49000001, 0)},
    [5] = {Image = "rbxassetid://16673814397", Size = UDim2.new(0, 158, 0, 186), Position = UDim2.new(0.519999981, 0, 0.5, 0)},
    [6] = {Image = "rbxassetid://16673778540", Size = UDim2.new(0, 216, 0, 251), Position = UDim2.new(0.514999986, 0, 0.479999989, 0)},
    [7] = {Image = "rbxassetid://16673778277", Size = UDim2.new(0, 240, 0, 243), Position = UDim2.new(0.505999982, 0, 0.5, 0)},
    [8] = {Image = "rbxassetid://16673778011", Size = UDim2.new(0, 315, 0, 305), Position = UDim2.new(0.535000026, 0, 0.439999998, 0)},
    [9] = {Image = "rbxassetid://16673777723", Size = UDim2.new(0, 315, 0, 315), Position = UDim2.new(0.504999995, 0, 0.493999988, 0)},
    [10] = {Image = "rbxassetid://16673777460", Size = UDim2.new(0, 350, 0, 383), Position = UDim2.new(0.49000001, 0, 0.479999989, 0)},
    [11] = {Image = "rbxassetid://16673777127", Size = UDim2.new(0, 471, 0, 475), Position = UDim2.new(0.476000011, 0, 0.5, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://16490483297", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(255, 255, 255), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(208, 208, 208))}), CurrentScoreStrokeColor = Color3.fromRGB(0, 0, 0)},
    NextFruit = {
        Image = "rbxassetid://16490483493",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {Cherry = {Image = "rbxassetid://16673779745", Size = UDim2.new(0.788999975, 0, 0.788999975, 0)}, Strawberry = {Image = "rbxassetid://16673779601", Size = UDim2.new(1.051, 0, 1.051, 0)}, Grapes = {Image = "rbxassetid://16673779236", Size = UDim2.new(1.20099998, 0, 1.20099998, 0)}, Orange = {Image = "rbxassetid://16673778944", Size = UDim2.new(1.35000002, 0, 1.35000002, 0)}, Tomato = {Image = "rbxassetid://16673814397", Size = UDim2.new(1.43700004, 0, 1.43700004, 0)}}
    },
    Info = {DropButtonImage = "rbxassetid://16674058813", InfographicImage = "rbxassetid://16674083853"},
    MobileControls = {MoveRightImage = "rbxassetid://16456391694", MoveLeftImage = "rbxassetid://16456392157"}
}
return tbl_1