-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Uncommon", Cost = 7500, CosmeticName = "Doodle Cat Skin Pack", ShopThumbnailImageId = "rbxassetid://137116754820172", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://17042719577"}
tbl_1.FruitBox = {Image = "rbxassetid://17041603908", TopBarColor = Color3.fromRGB(255, 219, 127)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://17041607851", Size = UDim2.new(0, 43, 0, 43), Position = UDim2.new(0.5, 0, 0.529999971, 0)},
    [2] = {Image = "rbxassetid://17041607577", Size = UDim2.new(0, 60, 0, 60), Position = UDim2.new(0.5, 0, 0.519999981, 0)},
    [3] = {Image = "rbxassetid://17041607180", Size = UDim2.new(0, 90, 0, 90), Position = UDim2.new(0.5, 0, 0.514999986, 0)},
    [4] = {Image = "rbxassetid://17041606875", Size = UDim2.new(0, 92, 0, 92), Position = UDim2.new(0.5, 0, 0.540000021, 0)},
    [5] = {Image = "rbxassetid://17041606549", Size = UDim2.new(0, 112, 0, 112), Position = UDim2.new(0.50999999, 0, 0.529999971, 0)},
    [6] = {Image = "rbxassetid://17041606325", Size = UDim2.new(0, 150, 0, 150), Position = UDim2.new(0.504999995, 0, 0.514999986, 0)},
    [7] = {Image = "rbxassetid://17041606113", Size = UDim2.new(0, 166, 0, 166), Position = UDim2.new(0.50999999, 0, 0.524999976, 0)},
    [8] = {Image = "rbxassetid://17041605867", Size = UDim2.new(0, 215, 0, 215), Position = UDim2.new(0.50999999, 0, 0.529999971, 0)},
    [9] = {Image = "rbxassetid://17041605456", Size = UDim2.new(0, 230, 0, 230), Position = UDim2.new(0.50999999, 0, 0.519999981, 0)},
    [10] = {Image = "rbxassetid://17041605055", Size = UDim2.new(0, 287, 0, 287), Position = UDim2.new(0.50999999, 0, 0.540000021, 0)},
    [11] = {Image = "rbxassetid://17041604736", Size = UDim2.new(0, 350, 0, 350), Position = UDim2.new(0.5, 0, 0.529999971, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://15044243217", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(74, 30, 8), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 238, 191)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 195, 84))}), CurrentScoreStrokeColor = Color3.fromRGB(74, 30, 8)},
    NextFruit = {
        Image = "rbxassetid://15044243766",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {
            Cherry = {Image = "rbxassetid://17041607851", Size = UDim2.new(0.310810804, 0, 0.310810804, 0)},
            Strawberry = {Image = "rbxassetid://17041607577", Size = UDim2.new(0.344594598, 0, 0.344594598, 0)},
            Grapes = {Image = "rbxassetid://17041607180", Size = UDim2.new(0.466216236, 0, 0.466216236, 0)},
            Orange = {Image = "rbxassetid://17041606875", Size = UDim2.new(0.533783793, 0, 0.533783793, 0)},
            Tomato = {Image = "rbxassetid://17041606549", Size = UDim2.new(0.695945919, 0, 0.695945919, 0)}
        }
    },
    Info = {DropButtonImage = "rbxassetid://17041620728", InfographicImage = "rbxassetid://17041603390"},
    MobileControls = {MoveRightImage = "rbxassetid://15300845665", MoveLeftImage = "rbxassetid://15300845942"}
}
return tbl_1