-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Epic", Cost = 15000, CosmeticName = "Ghost Skin Pack", ShopThumbnailImageId = "rbxassetid://89935299892887", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://16490154582"}
tbl_1.FruitBox = {Image = "rbxassetid://16490276887", TopBarColor = Color3.fromRGB(0, 0, 0)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://16490158894", Size = UDim2.new(0, 40, 0, 40), Position = UDim2.new(0.501999974, 0, 0.5, 0)},
    [2] = {Image = "rbxassetid://16490158512", Size = UDim2.new(0, 62, 0, 66), Position = UDim2.new(0.49000001, 0, 0.49000001, 0)},
    [3] = {Image = "rbxassetid://16490158006", Size = UDim2.new(0, 85, 0, 90), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [4] = {Image = "rbxassetid://16490157558", Size = UDim2.new(0, 116, 0, 88), Position = UDim2.new(0.479999989, 0, 0.469999999, 0)},
    [5] = {Image = "rbxassetid://16490157056", Size = UDim2.new(0, 107, 0, 105), Position = UDim2.new(0.469999999, 0, 0.485000014, 0)},
    [6] = {Image = "rbxassetid://16490156617", Size = UDim2.new(0, 195, 0, 150), Position = UDim2.new(0.5, 0, 0.479999989, 0)},
    [7] = {Image = "rbxassetid://16490155939", Size = UDim2.new(0, 197, 0, 162), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [8] = {Image = "rbxassetid://16490155779", Size = UDim2.new(0, 206, 0, 202), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [9] = {Image = "rbxassetid://16490155524", Size = UDim2.new(0, 223, 0, 229), Position = UDim2.new(0.5, 0, 0.465000004, 0)},
    [10] = {Image = "rbxassetid://16490155271", Size = UDim2.new(1.22099996, 0, 1.11199999, 0), Position = UDim2.new(0.479999989, 0, 0.5, 0)},
    [11] = {Image = "rbxassetid://16490155001", Size = UDim2.new(0, 331, 0, 371), Position = UDim2.new(0.479999989, 0, 0.501999974, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://16490483493", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(255, 255, 255), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 251, 251)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 251, 251))}), CurrentScoreStrokeColor = Color3.fromRGB(4, 4, 4)},
    NextFruit = {
        Image = "rbxassetid://16490483493",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {
            Cherry = {Image = "rbxassetid://16490158894", Size = UDim2.new(0.310810804, 0, 0.310810804, 0)},
            Strawberry = {Image = "rbxassetid://16490158512", Size = UDim2.new(0.344594598, 0, 0.344594598, 0)},
            Grapes = {Image = "rbxassetid://16490158006", Size = UDim2.new(0.466216236, 0, 0.466216236, 0)},
            Orange = {Image = "rbxassetid://16490157558", Size = UDim2.new(0.533783793, 0, 0.533783793, 0)},
            Tomato = {Image = "rbxassetid://16490157056", Size = UDim2.new(0.695945919, 0, 0.695945919, 0)}
        }
    },
    Info = {DropButtonImage = "rbxassetid://16490387941", InfographicImage = "rbxassetid://16490387426"},
    MobileControls = {MoveRightImage = "rbxassetid://16456391694", MoveLeftImage = "rbxassetid://16456392157"}
}
return tbl_1