-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Uncommon", Cost = 7000, CosmeticName = "Gumball Skin Pack", ShopThumbnailImageId = "rbxassetid://106393459284268", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://17384156429"}
tbl_1.FruitBox = {Image = "rbxassetid://17384159746", TopBarColor = Color3.fromRGB(255, 212, 248)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://17384779044", Size = UDim2.new(0, 42, 0, 48), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [2] = {Image = "rbxassetid://17384778642", Size = UDim2.new(0, 51, 0, 59), Position = UDim2.new(0.50999999, 0, 0.460000008, 0)},
    [3] = {Image = "rbxassetid://17384778377", Size = UDim2.new(0, 80, 0, 89), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [4] = {Image = "rbxassetid://17384778039", Size = UDim2.new(0, 84, 0, 84), Position = UDim2.new(0.5, 0, 0.483999997, 0)},
    [5] = {Image = "rbxassetid://17384777751", Size = UDim2.new(0, 103, 0, 120), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [6] = {Image = "rbxassetid://17384777477", Size = UDim2.new(0, 155, 0, 148), Position = UDim2.new(0.499000013, 0, 0.5, 0)},
    [7] = {Image = "rbxassetid://17384777101", Size = UDim2.new(0, 180, 0, 180), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [8] = {Image = "rbxassetid://17384776742", Size = UDim2.new(1.29999995, 0, 1.20000005, 0), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [9] = {Image = "rbxassetid://17384776172", Size = UDim2.new(0, 240, 0, 230), Position = UDim2.new(0.50999999, 0, 0.5, 0)},
    [10] = {Image = "rbxassetid://17384775909", Size = UDim2.new(0, 277, 0, 284), Position = UDim2.new(0.49000001, 0, 0.49000001, 0)},
    [11] = {Image = "rbxassetid://17384775509", Size = UDim2.new(1.22000003, 0, 1, 0), Position = UDim2.new(0.5, 0, 0.5, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://15044243217", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(74, 30, 8), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 238, 191)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 195, 84))}), CurrentScoreStrokeColor = Color3.fromRGB(74, 30, 8)},
    NextFruit = {
        Image = "rbxassetid://15044243766",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {
            Cherry = {Image = "rbxassetid://17384779044", Size = UDim2.new(0.310810804, 0, 0.310810804, 0)},
            Strawberry = {Image = "rbxassetid://17384778642", Size = UDim2.new(0.344594598, 0, 0.344594598, 0)},
            Grapes = {Image = "rbxassetid://17384778377", Size = UDim2.new(0.466216236, 0, 0.466216236, 0)},
            Orange = {Image = "rbxassetid://17384778039", Size = UDim2.new(0.533783793, 0, 0.533783793, 0)},
            Tomato = {Image = "rbxassetid://17384777751", Size = UDim2.new(0.695945919, 0, 0.695945919, 0)}
        }
    },
    Info = {DropButtonImage = "rbxassetid://17384159053", InfographicImage = "rbxassetid://17384588274"},
    MobileControls = {MoveRightImage = "rbxassetid://15300845665", MoveLeftImage = "rbxassetid://15300845942"}
}
return tbl_1