-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Legendary", Cost = 30000, CosmeticName = "Meme Skin Pack", ShopThumbnailImageId = "rbxassetid://95843025336137", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://16583834874"}
tbl_1.FruitBox = {Image = "rbxassetid://16582700813", TopBarColor = Color3.fromRGB(255, 255, 255)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://16582633974", Size = UDim2.new(0, 40, 0, 35), Position = UDim2.new(0.501999974, 0, 0.5, 0)},
    [2] = {Image = "rbxassetid://16582633680", Size = UDim2.new(0, 62, 0, 50), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [3] = {Image = "rbxassetid://16582633386", Size = UDim2.new(0, 85, 0, 90), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [4] = {Image = "rbxassetid://16582632929", Size = UDim2.new(0, 116, 0, 88), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [5] = {Image = "rbxassetid://16582632530", Size = UDim2.new(0, 107, 0, 105), Position = UDim2.new(0.49000001, 0, 0.485000014, 0)},
    [6] = {Image = "rbxassetid://16582632210", Size = UDim2.new(0, 195, 0, 150), Position = UDim2.new(0.49000001, 0, 0.495000005, 0)},
    [7] = {Image = "rbxassetid://16582631983", Size = UDim2.new(0, 197, 0, 162), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [8] = {Image = "rbxassetid://16582631737", Size = UDim2.new(0, 206, 0, 202), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [9] = {Image = "rbxassetid://16582631479", Size = UDim2.new(0, 213, 0, 229), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [10] = {Image = "rbxassetid://16582631239", Size = UDim2.new(0, 255, 0, 271), Position = UDim2.new(0.50999999, 0, 0.495999992, 0)},
    [11] = {Image = "rbxassetid://16582631012", Size = UDim2.new(0, 311, 0, 325), Position = UDim2.new(0.479999989, 0, 0.500999987, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://16490483493", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(255, 255, 255), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 251, 251)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 251, 251))}), CurrentScoreStrokeColor = Color3.fromRGB(4, 4, 4)},
    NextFruit = {
        Image = "rbxassetid://16490483493",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {
            Cherry = {Image = "rbxassetid://16582633974", Size = UDim2.new(0.310810804, 0, 0.310810804, 0)},
            Strawberry = {Image = "rbxassetid://16582633680", Size = UDim2.new(0.344594598, 0, 0.344594598, 0)},
            Grapes = {Image = "rbxassetid://16582633386", Size = UDim2.new(0.466216236, 0, 0.466216236, 0)},
            Orange = {Image = "rbxassetid://16582632929", Size = UDim2.new(0.533783793, 0, 0.533783793, 0)},
            Tomato = {Image = "rbxassetid://16582632530", Size = UDim2.new(0.695945919, 0, 0.695945919, 0)}
        }
    },
    Info = {DropButtonImage = "rbxassetid://16582630463", InfographicImage = "rbxassetid://16582629970"},
    MobileControls = {MoveRightImage = "rbxassetid://16456391694", MoveLeftImage = "rbxassetid://16456392157"}
}
return tbl_1