-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Uncommon", Cost = 7500, CosmeticName = "Oceanic Skin Pack", ShopThumbnailImageId = "rbxassetid://123537087846778", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://16827984764"}
tbl_1.FruitBox = {Image = "rbxassetid://16828600397", TopBarColor = Color3.fromRGB(255, 255, 255)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://16827951664", Size = UDim2.new(0, 36, 0, 43), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [2] = {Image = "rbxassetid://16827996632", Size = UDim2.new(0, 55, 0, 52), Position = UDim2.new(0.5, 0, 0.50999999, 0)},
    [3] = {Image = "rbxassetid://16827951373", Size = UDim2.new(0, 76, 0, 76), Position = UDim2.new(0.50999999, 0, 0.5, 0)},
    [4] = {Image = "rbxassetid://16827951124", Size = UDim2.new(0, 82, 0, 82), Position = UDim2.new(0.5, 0, 0.49000001, 0)},
    [5] = {Image = "rbxassetid://16827950789", Size = UDim2.new(0, 98, 0, 98), Position = UDim2.new(0.504999995, 0, 0.5, 0)},
    [6] = {Image = "rbxassetid://16827996377", Size = UDim2.new(0, 134, 0, 134), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [7] = {Image = "rbxassetid://16827950405", Size = UDim2.new(0, 147, 0, 147), Position = UDim2.new(0.49000001, 0, 0.5, 0)},
    [8] = {Image = "rbxassetid://16827950194", Size = UDim2.new(0, 195, 0, 200), Position = UDim2.new(0.5, 0, 0.467999995, 0)},
    [9] = {Image = "rbxassetid://16827984925", Size = UDim2.new(0, 240, 0, 220), Position = UDim2.new(0.49000001, 0, 0.5, 0)},
    [10] = {Image = "rbxassetid://16827949862", Size = UDim2.new(0, 260, 0, 264), Position = UDim2.new(0.479999989, 0, 0.485000014, 0)},
    [11] = {Image = "rbxassetid://16827949664", Size = UDim2.new(0, 310, 0, 343), Position = UDim2.new(0.519999981, 0, 0.5, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://16490483493", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(255, 255, 255), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 251, 251)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 251, 251))}), CurrentScoreStrokeColor = Color3.fromRGB(4, 4, 4)},
    NextFruit = {
        Image = "rbxassetid://16490483493",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {
            Cherry = {Image = "rbxassetid://16827951664", Size = UDim2.new(0.310810804, 0, 0.310810804, 0)},
            Strawberry = {Image = "rbxassetid://16827996632", Size = UDim2.new(0.344594598, 0, 0.344594598, 0)},
            Grapes = {Image = "rbxassetid://16827951373", Size = UDim2.new(0.466216207, 0, 0.466216207, 0)},
            Orange = {Image = "rbxassetid://16827951124", Size = UDim2.new(0.533783793, 0, 0.533783793, 0)},
            Tomato = {Image = "rbxassetid://16827950789", Size = UDim2.new(0.695945919, 0, 0.695945919, 0)}
        }
    },
    Info = {DropButtonImage = "rbxassetid://16827949492", InfographicImage = "rbxassetid://16827949199"},
    MobileControls = {MoveRightImage = "rbxassetid://16456391694", MoveLeftImage = "rbxassetid://16456392157"}
}
return tbl_1