-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local tbl_1 = {Rarity = "Uncommon", Cost = 7500, CosmeticName = "Shark Skin Pack", ShopThumbnailImageId = "rbxassetid://78749938953789", CurrencyType = "Coins"}
tbl_1.Slots = {"Background", "Dropper", "FruitBox", "Fruits"}
tbl_1.Background = {Image = "rbxassetid://16754693864"}
tbl_1.FruitBox = {Image = "rbxassetid://16754734096", TopBarColor = Color3.fromRGB(255, 255, 255)}
tbl_1.Fruits = {
    [1] = {Image = "rbxassetid://16754696947", Size = UDim2.new(0, 39, 0, 44), Position = UDim2.new(0.49000001, 0, 0.49000001, 0)},
    [2] = {Image = "rbxassetid://16754696625", Size = UDim2.new(0, 56, 0, 59), Position = UDim2.new(0.50999999, 0, 0.50999999, 0)},
    [3] = {Image = "rbxassetid://16754734285", Size = UDim2.new(0, 85, 0, 85), Position = UDim2.new(0.5, 0, 0.50999999, 0)},
    [4] = {Image = "rbxassetid://16754696046", Size = UDim2.new(0, 86, 0, 86), Position = UDim2.new(0.5, 0, 0.50999999, 0)},
    [5] = {Image = "rbxassetid://16754695735", Size = UDim2.new(0, 105, 0, 105), Position = UDim2.new(0.504999995, 0, 0.479999989, 0)},
    [6] = {Image = "rbxassetid://16754695431", Size = UDim2.new(0, 149, 0, 158), Position = UDim2.new(0.50999999, 0, 0.50999999, 0)},
    [7] = {Image = "rbxassetid://16754695031", Size = UDim2.new(0, 160, 0, 160), Position = UDim2.new(0.5, 0, 0.5, 0)},
    [8] = {Image = "rbxassetid://16754694844", Size = UDim2.new(0, 210, 0, 215), Position = UDim2.new(0.519999981, 0, 0.467999995, 0)},
    [9] = {Image = "rbxassetid://16754694592", Size = UDim2.new(0, 220, 0, 215), Position = UDim2.new(0.49000001, 0, 0.5, 0)},
    [10] = {Image = "rbxassetid://16754694160", Size = UDim2.new(0, 265, 0, 264), Position = UDim2.new(0.501999974, 0, 0.5, 0)},
    [11] = {Image = "rbxassetid://16754693984", Size = UDim2.new(0, 333, 0, 343), Position = UDim2.new(0.479999989, 0, 0.49000001, 0)}
}
tbl_1.Hud = {
    Score = {Image = "rbxassetid://16490483493", Position = UDim2.new(0, 0, 0, 0), Size = UDim2.new(1, 0, 1, 0), AnchorPoint = Vector2.new(0, 0), BestScoreTextColor = Color3.fromRGB(255, 255, 255), CurrentScoreGradient = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(251, 251, 251)), ColorSequenceKeypoint.new(1, Color3.fromRGB(251, 251, 251))}), CurrentScoreStrokeColor = Color3.fromRGB(4, 4, 4)},
    NextFruit = {
        Image = "rbxassetid://16490483493",
        Size = UDim2.new(1, 0, 1, 0),
        FruitCycle = {
            Cherry = {Image = "rbxassetid://16754696947", Size = UDim2.new(0.310810804, 0, 0.310810804, 0)},
            Strawberry = {Image = "rbxassetid://16754696625", Size = UDim2.new(0.344594598, 0, 0.344594598, 0)},
            Grapes = {Image = "rbxassetid://16754734285", Size = UDim2.new(0.466216207, 0, 0.466216207, 0)},
            Orange = {Image = "rbxassetid://16754696046", Size = UDim2.new(0.533783793, 0, 0.533783793, 0)},
            Tomato = {Image = "rbxassetid://16754695735", Size = UDim2.new(0.695945919, 0, 0.695945919, 0)}
        }
    },
    Info = {DropButtonImage = "rbxassetid://16754693515", InfographicImage = "rbxassetid://16754693132"},
    MobileControls = {MoveRightImage = "rbxassetid://16456391694", MoveLeftImage = "rbxassetid://16456392157"}
}
return tbl_1